# Generated by Django 5.1.2 on 2024-10-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
    ]
