# Generated by Django 5.1.2 on 2024-11-01 09:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_reservation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guests_count",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
